////
  //
  // Copyright 2025-2026 gematik GmbH
  //
  // Licensed under the Apache License, Version 2.0 (the "License");
  // you may not use this file except in compliance with the License.
  // You may obtain a copy of the License at
  //
  //     http://www.apache.org/licenses/LICENSE-2.0
  //
  // Unless required by applicable law or agreed to in writing, software
  // distributed under the License is distributed on an "AS IS" BASIS,
  // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  // See the License for the specific language governing permissions and
  // limitations under the License.
  //
  // *******
  //
  // For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
////

== How to integrate custom PS (Primärsystem)

[NOTE]
====
ZETA is only configured for the VSDM-Server, not the PoPP-Server.
====

Integrating a custom Primärsystem (PS) is a primary design goal of the TI 2.0
Testhub. Currently, however, it requires some manual steps:

* Set `pssim.active=false` in the file `tiger/flags.yaml` to disable the
existing PS-Simulator. This can also be done via environment eariables
(`PSSIM_ACTIVE=false`).

* The custom PS has to be started (e.g. add as a new service in
doc/docker/backend/compose-local.yaml, but could simply be started outside of
docker compose as well)

* Optional: To use the PS with the VSDM-Testsuite it has to implement the same
API as the existing vsdm-client (which can be seen at
http://localhost:8220/v3/api-docs)

You can connect to the resource servers as follows:

VSDM-Server:: Use the port that is forwarded to the internal port 443 of
`vsdm-zeta-ingress`. If the port is 9119 you can connect from the Docker host
using https://localhost:9119/.

PoPP-Server:: Use the port that is forwarded to the internal port 80 of
   `popp-ingress`.

The usage of the Zeta-SDK can be seen in the existing
vsdm-client-simservice-java implementation. The class `ZetaSdkClientAdapter.java`
uses the client while `VsdmZetaSdkClientConfig.java` configures it.
