tigerProxy:
  name: remote-tiger-proxy
  proxyPort: 9090
  adminPort: 8080
  additionalProxyPorts:
    - 8081
    - 8082
    - 8443
    - 443
    - 80
    - 8181
  tls:
    serverRootCa: "tiger-config/tigerProxy.p12"
#    masterSecretsFile: /tmp/secrets.txt
    alternativeNames:
        - "popp-ingress"
        - "vsdm-zeta-ingress"
  activateRbelParsingFor:
    - websocket
    - erp-vau
  proxyRoutes:
    - from: /
      to: http://popp-client:8081/
      matchForProxyType: false
      hosts:
        - "popp-client"
    - from: /
      to: http://popp-client-erp:8081
      hosts: ["popp-client-erp"]
      matchForProxyType: false
    - from: /
      to: http://vsdm-zeta-pdp-opa:8181/
      hosts: ["vsdm-zeta-pdp-opa"]
      matchForProxyType: false


    # route für IdP in RU/RU-DEV
    - from: /
      to: https://10.31.196.4:443/
      hosts: ["idp-ref.zentral.idp.splitdns.ti-dienste.de"]
    # route für IdP in TU
    - from: /
      to: https://172.31.197.4:443/
      hosts: ["idp-test.zentral.idp.splitdns.ti-dienste.de"]

    # route für eRp TU Fachdienst
    - from: /
      to: https://172.31.194.10:443/
      hosts: ["erp-test.zentral.erp.splitdns.ti-dienste.de", "erp-test.app.ti-dienste.de"]
    # route für eRp RU Fachdienst
    - from: /
      to: https://10.31.195.10:443/
      hosts: ["erp-ref.zentral.erp.splitdns.ti-dienste.de", "erp-ref.app.ti-dienste.de"]
    # route für eRp RU-DEV Fachdienst
    - from: /
      to: https://10.31.194.12:443/
      hosts: ["erp-dev.zentral.erp.splitdns.ti-dienste.de", "erp-dev.app.ti-dienste.de"]

  rewriteHostHeader: false
  honorHostHeaderRouting: true
