tigerProxy:
  proxyPort: 9090
  adminPort: 8080
  tls:
    serverRootCa: "tigerProxy.p12"
  activateRbelParsingFor:
    - websocket
    - x509
  proxyRoutes:
    - from: http://vsdm-zeta-ingress:443
      to: https://vsdm-zeta-ingress:443/
      matchForProxyType: false
      preserveHostHeader: true
    - from: https://vsdm-zeta-ingress
      to: https://vsdm-zeta-ingress:443/
      matchForProxyType: false
      preserveHostHeader: true
  rewriteHostHeader: false
