openapi: 3.0.0
info:
  title: ZETA PDP Server Mock
  description: API zum Simulieren eines ZETA PDP Servers.
  version: 1.0.0
servers:
  - url: http://localhost:9102
    description: Local Dev-Server

paths:
  /token:

    post:
      summary: Abfrage des Access Tokens vom ZETA PDP Server Mock
      description: Gibt aktuell einen Access und Refresh Token zur端ck.
      responses:
        '200':
          description: Erfolgreiche R端ckgabe der Token

  /service/status:

    get:
      summary: Abfrage des ZETA PDP Server Mock Status
      description: Gibt aktuell nur ein leeres Formular zur端ck.
      responses:
        '200':
          description: Erfolgreiche R端ckgabe des ZETA PDP Server Mock Status
