server:
  port: 8220

otel:
  sdk:
    disabled: true

popp:
  http:
    url: http://popp-client:8081/token
  ws:
    url: ws://localhost:9110

vsdm:
  resourceServerUrl: http://localhost:9120
  use-mock-popp-token: true
  popp-token-generator-url: http://localhost:9500

zetasdk:
  smcbAlias: "alias"
  smcbPrivateKeyPassword: "00"
  smcbPrivateKeyPath: "doc/docker/backend/zeta/smcb-private/smcb_private.p12"
