server:
  port: 8220

otel:
  sdk:
    disabled: true

popp:
  http:
    url: http://localhost:9110
  ws:
    url: ws://localhost:9110

vsdm:
  resourceServerUrl: http://localhost:9120
  use-mock-popp-token: false
  popp-token-generator-url: http://localhost:9500

zetasdk:
  smcbAliasPath: "doc/docker/backend/zeta/smcb-private/smcb_private.alias.txt"
  smcbPrivateKeyPasswordPath: "doc/docker/backend/zeta/smcb-private/smcb_private.pw.txt"
  smcbPrivateKeyPath: "doc/docker/backend/zeta/smcb-private/smcb_private.p12"
