/*
 *
 * Copyright 2026 gematik GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
 */

package de.gematik.ti20.popp;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import de.gematik.test.tiger.glue.HttpGlueCode;
import de.gematik.test.tiger.lib.rbel.RbelMessageRetriever;
import de.gematik.test.tiger.lib.rbel.RbelValidator;
import de.gematik.test.tiger.lib.rbel.RequestParameter;
import de.gematik.ti20.popp.validation.ApduValidator;
import de.gematik.ti20.popp.validation.PoppTokenValidator;
import io.cucumber.java.de.Angenommen;
import io.cucumber.java.de.Dann;
import io.cucumber.java.de.Und;
import io.cucumber.java.de.Wenn;
import io.restassured.http.Method;
import java.net.URI;
import java.util.Objects;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Steps {

  HttpGlueCode httpGlueCode = new HttpGlueCode();
  private String communicationType = "";
  private RbelMessageRetriever rbelMessageRetriever;
  private RbelValidator rbelValidator;
  private ApduValidator apduValidator;
  private PoppTokenValidator poppTokenValidator;

  public Steps(
      RbelMessageRetriever rbelMessageRetriever,
      RbelValidator rbelValidator,
      ApduValidator apduValidator,
      PoppTokenValidator poppTokenValidator) {
    this.rbelMessageRetriever = rbelMessageRetriever;
    this.rbelValidator = new RbelValidator();
    this.apduValidator = new ApduValidator();
    this.poppTokenValidator = new PoppTokenValidator();
  }

  public Steps() {
    this(RbelMessageRetriever.getInstance());
    this.rbelValidator = new RbelValidator();
    this.apduValidator = new ApduValidator();
    this.poppTokenValidator = new PoppTokenValidator();
  }

  public Steps(RbelMessageRetriever instance) {}

  @Angenommen("das Primärsystem hat einen gültigen Access- und Refresh-Token vom ZETA Guard")
  public void primaersystem_hat_token() {
    // Access Token mit SMC-B
  }

  @Wenn("das Primärsystem den PoPP-Token vom PoPP-Service abfragt")
  public void psRequestsPoppToken() {
    requestPoppToken();
  }

  @Und("das PoPP-Token ist vollständig und spezifikationskonform")
  public void tokenIsCorrect() {
    if (communicationType.contains("connector")) {
      poppTokenValidator.validatePoppTokenforEHealthKT();
    } else {
      poppTokenValidator.validatePoppTokenforStandardKt();
    }
  }

  @Angenommen("der Versicherte in der LEI präsentiert seine eGK {string} am Lesegerät {string}")
  public void derVersichertePreasentiertEgk(final String readerType, final String commType) {
    communicationType = CommunicationType.from(readerType, commType).getValue();
    log.info("Nutze {} für die Kommunikation", communicationType);
  }

  @Dann("erhält das Primärsystem den Fehlercode {string} und den Text {string} vom PoPP-Service")
  public void validatePoppError(final String errorCode, final String errorMessage) {
    this.rbelMessageRetriever.filterRequestsAndStoreInContext(
        RequestParameter.builder().path(".*/token").build().resolvePlaceholders());
    this.rbelValidator.assertAttributeOfCurrentResponseMatches(
        "$.body.status", errorMessage, true, this.rbelMessageRetriever);
  }

  private void requestPoppToken() {
    // StartMessage mit cardConnectionType commType-readerType
    // if (readerType == connector) => clientSessionId must be generated by connector (SOAP call
    // StartCardSession

    final ObjectMapper mapper = new ObjectMapper();
    final ObjectNode json = mapper.createObjectNode();
    json.put("communicationType", communicationType);
    json.put("clientSessionId", "123456");

    final String jsonBody = json.toString();

    httpGlueCode.sendRequestWithMultiLineBody(
        Method.POST, URI.create("http://localhost:8081/token"), "application/json", jsonBody);
  }

  @Und("die empfangenen APDUs sind korrekt {string}")
  public void dieEmpfangenenAPDUsSindKorrekt(String readerType) {
    if (Objects.equals(readerType, "Standardleser") || Objects.equals(readerType, "virtuell")) {
      apduValidator.validateApdusforStdKT();
    } else if (Objects.equals(readerType, "eH-KT")) {
      apduValidator.validateApdusforEHealthKT();
    } else {
      throw new IllegalArgumentException(
          "Unsupported reader type: "
              + readerType
              + ". Expected 'Standardleser', 'virtuell', or 'eH-KT'.");
    }
  }
}
