worker_processes  auto;

load_module modules/libngx_pep.so;

error_log  /dev/stdout debug;
pid        /tmp/nginx.pid;


events {
    worker_connections 1024;
    multi_accept       on;
    use                epoll;
}

http {
    include       /etc/nginx/mime.types;
    include       /etc/nginx/templates/common.conf;

    access_log  /dev/stdout  main;


    keepalive_timeout  65;

    gzip  on;

    pep_pdp_issuer https://popp-zeta-ingress/auth/realms/zeta-guard;
    pep_http_client_accept_invalid_certs on;
    pep_require_popp    off;
    pep_popp_issuer http://popp-server:8443;


    include /etc/nginx/conf.d/*.conf;
}
