services:
  popp-client-erp:
    profiles: [ "full" ]
    image: gematik1/popp-client:2.7.0
    platform: linux/amd64
    container_name: ${COMPOSE_PROJECT_NAME}-popp-client-erp
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ZETA_AUTHENTICATION_SMB_KEYFILE=/mnt/smcb_private.p12
      - POPP_SERVER_URL=${POPP_SERVER_URL:-wss://popp.dev.poppservice.de:443/popp/practitioner/api/v1/token-generation-ehc}
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013"
      - VIRTUAL_CARD_IMAGE_FILE=/data/cards/egkCardImage.xml

      # Konnektor configuration
      - CONNECTOR_END_POINT_URL=${CONNECTOR_END_POINT_URL:-https://kon9.ksp.ltuzd.telematik-test}
      - CONNECTOR_SECURE_KEYSTORE=${CONNECTOR_SECURE_KEYSTORE:-/mnt/konnektor/kon9_CS1.p12}
      - CONNECTOR_SECURE_KEYSTORE_PASSWORD=${CONNECTOR_SECURE_KEYSTORE_PASSWORD:-123456}
      - CONNECTOR_SECURE_TRUSTSTORE=${CONNECTOR_SECURE_TRUSTSTORE:-/mnt/erpe2e_truststore.p12}
      - CONNECTOR_SECURE_TRUSTSTORE_PASSWORD=${CONNECTOR_SECURE_TRUSTSTORE_PASSWORD:-123456}

      - CONTEXT_CLIENT_SYSTEM_ID=${CONTEXT_CLIENT_SYSTEM_ID:-CS1}
      - CONTEXT_WORKPLACE_ID=${CONTEXT_WORKPLACE_ID:-AP1}
      - CONTEXT_MANDANT_ID=${CONTEXT_MANDANT_ID:-Mandant1}
      - CARD_TERMINAL_ID=${CARD_TERMINAL_ID:-e526d874-e1fb-4b88-b55f-930a5ca7baab}
#      - CARD_TERMINAL_SLOT=${CARD_TERMINAL_SLOT}
    networks:
      - testhub_network
    ports:
      - "${PORT_POPP_CLIENT_ERP:?PORT_POPP_CLIENT_ERP_missing_set_it_in_doc/docker/.env}:8081"
      - "${PORT_POPP_CLIENT_ERP_MGMT:?PORT_POPP_CLIENT_ERP_MGMT_missing_set_it_in_doc/docker/.env}:9001"
    volumes:
      - ../../../no-publish/test-data/erp:/mnt/
      - ../../../test/vsdm-testsuite/src/test/resources/data/cards:/data/cards/
