tigerProxy:
  proxyPort: 80
  adminPort: 8080
  activateRbelParsingFor:
    - websocket
  proxyRoutes:
    - from: /auth
      to: http://popp-zeta-pdp
    - from: /
      to: http://popp-zeta-pep
  modifications:
    - condition: '$.path =^ "/auth/realms/zeta-guard/"'
      targetElement: "$.header.X-Forwarded-For"
      replaceWith: "popp-zeta-pdp"
    - condition: '$.path =^ "/auth/realms/zeta-guard/"'
      targetElement: "$.header.X-Forwarded-Host"
      replaceWith: "popp-zeta-pdp"
    - condition: '$.path =^ "/auth/realms/zeta-guard/"'
      targetElement: "$.header.X-Forwarded-Scheme"
      replaceWith: "https"
    - condition: '$.path =^ "/auth/realms/zeta-guard/"'
      targetElement: "$.header.X-Forwarded-Proto"
      replaceWith: "https"
    - condition: '$.path =^ "/auth/realms/zeta-guard/"'
      targetElement: "$.header.X-Forwarded-Proto"
      replaceWith: "https"
