server:
  port: ${SERVER_PORT:9130}

otel:
  sdk:
    disabled: true

vsdm:
  path-to-test-data: ${VSDM_PATH_TO_TEST_DATA:./public-test-data}
  iknr: 109500969
  valid-kvnr-prefix: X1
  invalid-kvnr-prefix: X4
  unknown-kvnr-prefix: X9
